name: CI-Linter-Formatter

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./mefolio
        run: npm ci

      - name: Run formatter check
        working-directory: ./mefolio
        run: npx prettier --check .

      - name: Run linter check
        working-directory: ./mefolio
        run: npm run lint

